'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const number=new Intl.NumberFormat('pt-BR'), decimal=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const fmt=n=>number.format(n), pct=n=>decimal.format(n)+'%', percent=(a,b)=>b?a/b*100:0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=s=>s.toLocaleLowerCase('pt-BR').replace(/(^|\s)\S/g,c=>c.toLocaleUpperCase('pt-BR'));
const normalized=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const colors={'15':'#c73e50','44':'#3779bd','14':'#6c829a','55':'#678db4','50':'#af797a','35':'#9a9b71','28':'#8f7f9d'};
// Escala comum: vantagem do primeiro sobre o segundo / votos válidos (0–100 p.p.).
function voteMargin(a){return a?.valid?percent((a.ranking[0]?.[1]||0)-(a.ranking[1]?.[1]||0),a.valid):0;}
function voteHeat(a){if(!a?.valid)return '#e1e7e5';if(voteMargin(a)===0)return '#88939d';const end=({'15':'#b8233a','44':'#205da2'}[a.ranking[0][0]]||colors[a.ranking[0][0]]||'#88939d'),t=.12+.88*Math.min(1,voteMargin(a)/100);return '#'+[1,3,5].map((i,k)=>Math.round([250,247,244][k]*(1-t)+parseInt(end.slice(i,i+2),16)*t).toString(16).padStart(2,'0')).join('');}
function heatLegend(){return '<span class="heat-legend">Intensidade = vantagem sobre o 2º colocado · 0–100 p.p.<i></i>Disputa próxima → vantagem maior</span>';}
const names={'15':'Paulo Dantas','44':'Rodrigo Cunha','14':'Collor','55':'Rui Palmeira','50':'Cícero Albuquerque','35':'Bombeiro Luciano','28':'Luciano Almeida'};
const state={turn:2,city:'',neighborhood:'',section:'',candidate:'',metric:'winner',page:0,search:'',sort:'valid',direction:-1};
let data,geo,census,mapLocations,neighborhoodGeo,charts={},groups=[],filtered=[],cityGroups,ageGroups;
const chartBase={animationDuration:350,textStyle:{fontFamily:'Segoe UI, Arial, sans-serif'},aria:{enabled:true},tooltip:{confine:true,backgroundColor:'#fff',borderColor:'#e1e8e8',textStyle:{color:'#173544',fontSize:12},extraCssText:'box-shadow:0 8px 30px #17354415;border-radius:8px;padding:12px;'}};
function setChart(id,option){if(!charts[id])charts[id]=echarts.init($('#'+id),null,{renderer:'svg'});charts[id].setOption({...chartBase,...option},true);return charts[id]}
function selected(turn=state.turn,territory=true){return data.sections.filter(s=>s.turn===turn&&(!state.city||s.city===state.city)&&(!territory||!state.neighborhood||s.neighborhood===state.neighborhood)&&(!territory||!state.section||s.id===state.section));}
function aggregate(rows){const a={apt:0,attendance:0,absent:0,votes:{},profile:{total:0,sex:{},age:{},education:{}},count:rows.length};for(const s of rows){for(const k of ['apt','attendance','absent'])a[k]+=s[k];for(const[n,v]of Object.entries(s.votes))a.votes[n]=(a.votes[n]||0)+v;for(const d of ['sex','age','education'])for(const[n,v]of Object.entries(s.profile[d]))a.profile[d][n]=(a.profile[d][n]||0)+v;a.profile.total+=s.profile.total;}a.valid=Object.entries(a.votes).reduce((t,[n,v])=>t+(data.candidates[n].type==='Nominal'?v:0),0);a.ranking=Object.entries(a.votes).filter(([n])=>data.candidates[n].type==='Nominal').sort((a,b)=>b[1]-a[1]);return a;}
const territorialFilters={};
function syncFilters(){
 const scoped=data.sections.filter(s=>s.turn===state.turn);
 const cityCounts={};for(const s of scoped)cityCounts[s.city]=(cityCounts[s.city]||0)+1;
 territorialFilters.city.update(Object.entries(data.cities).sort((a,b)=>a[1].name.localeCompare(b[1].name,'pt-BR')).map(([value,c])=>({value,label:title(c.name),detail:fmt(cityCounts[value]||0)+' seções com boletim'})),state.city);
 const neighborhoods=Object.entries(data.neighborhoods[state.city]||{}).sort((a,b)=>a[1].name.localeCompare(b[1].name,'pt-BR'));
 territorialFilters.neighborhood.update(neighborhoods.map(([value,n])=>({value,label:n.name,detail:fmt(scoped.filter(s=>s.city===state.city&&s.neighborhood===value).length)+' seções com boletim'})),state.neighborhood,!state.city,'Selecione um município');
 const sections=scoped.filter(s=>s.city===state.city&&s.neighborhood===state.neighborhood).sort((a,b)=>a.section-b.section||a.id.localeCompare(b.id));
 territorialFilters.section.update(sections.map(s=>({value:s.id,label:'Seção '+s.section.padStart(4,'0'),detail:title(s.place||'Local não informado')})),state.section,!state.neighborhood,'Selecione um bairro');
 $$('#turns button').forEach(b=>{b.classList.toggle('selected',+b.dataset.turn===state.turn);b.setAttribute('aria-pressed',+b.dataset.turn===state.turn)});
 $('#map-metric').value=state.metric;
 const crumbs=[['','Alagoas']];if(state.city)crumbs.push(['city',title(data.cities[state.city].name)]);if(state.neighborhood)crumbs.push(['neighborhood',data.neighborhoods[state.city][state.neighborhood].name]);if(state.section)crumbs.push(['section','Seção '+state.section.split('-').pop()]);
 $('#breadcrumbs').innerHTML=crumbs.map(([k,v])=>`<button data-level="${k}">${esc(v)}</button>`).join('<span>›</span>');
 $('#coverage').textContent=`${state.turn}º turno · ${fmt(selected().length)} seções com BU`;
 const params=new URLSearchParams();for(const k of ['turn','city','neighborhood','section','candidate','metric'])if(state[k])params.set(k,state[k]);history.replaceState(null,'','?'+params);
}
function navigate(patch){Object.assign(state,patch,{page:0,search:''});$('#table-search').value='';syncFilters();render();}
function render(){const rows=selected(),a=aggregate(rows);$('#status').hidden=true;
 const values=[['Eleitores aptos',a.apt,'Base dos boletins de urna'],['Comparecimento',a.attendance,pct(percent(a.attendance,a.apt))+' dos aptos'],['Abstenção',a.absent,pct(percent(a.absent,a.apt))+' dos aptos'],['Votos válidos',a.valid,pct(percent(a.valid,a.attendance))+' dos votos'],['Votos brancos',a.votes['95']||0,pct(percent(a.votes['95']||0,a.attendance))+' dos votos'],['Votos nulos',a.votes['96']||0,pct(percent(a.votes['96']||0,a.attendance))+' dos votos']];
 $('#kpis').innerHTML=values.map(([label,value,note],i)=>`<article class="kpi ${i===3?'primary':''}"><div class="kpi-label">${label}<span aria-hidden="true">${['◉','↗','↘','✓','□','⊘'][i]}</span></div><strong>${fmt(value)}</strong><small>${note}</small></article>`).join('');
 renderResults(a);renderMap();renderSectionGrid();renderProfile(a,rows);renderCensus();renderTable();
}
function renderResults(a){$('#result-title').textContent=`Resultado do ${state.turn}º turno`;const leader=a.ranking[0],second=a.ranking[1];
 $('#result-summary').innerHTML=leader?`<div><p>Mais votado no recorte</p><strong>${esc(names[leader[0]]||data.candidates[leader[0]].name)}</strong><small>${state.city?esc(title(data.cities[state.city].name)):'Alagoas'}${state.section?' · Seção '+state.section.split('-').pop():state.neighborhood?' · '+esc(data.neighborhoods[state.city][state.neighborhood].name):''}</small></div><div><strong>${pct(percent(leader[1],a.valid))}</strong><small>${second?fmt(leader[1]-second[1])+' votos de vantagem':'dos votos válidos'}</small></div>`:'<p>Sem votos neste recorte.</p>';
 $('#candidate-list').innerHTML=a.ranking.map(([n,v])=>`<button class="candidate ${state.candidate===n?'highlighted':''}" data-candidate="${n}" aria-pressed="${state.candidate===n}" style="--candidate:${colors[n]};--candidate-light:${colors[n]}16"><div class="candidate-top"><span class="avatar">${n}</span><div class="candidate-info">${esc(names[n]||data.candidates[n].name)}<small>${esc(data.candidates[n].party)} · ${n}</small></div><div class="candidate-numbers">${pct(percent(v,a.valid))}<small>${fmt(v)} votos</small></div></div><div class="bar-track"><div class="bar-fill" style="width:${percent(v,a.valid)}%"></div></div></button>`).join('');$('#clear-candidate').hidden=!state.candidate;
 const one=aggregate(selected(1)),two=aggregate(selected(2));let ns=['15','44'];if(state.candidate&&!ns.includes(state.candidate))ns.push(state.candidate);
 setChart('compare-chart',{legend:{bottom:6,itemWidth:8,itemHeight:8,textStyle:{fontSize:9,color:'#647e88'}},grid:{top:15,left:100,right:35,bottom:35},xAxis:{type:'value',show:false,max:100},yAxis:{type:'category',inverse:true,data:ns.map(n=>names[n]),axisLine:{show:false},axisTick:{show:false},axisLabel:{fontSize:10,color:'#526b77'}},tooltip:{...chartBase.tooltip,trigger:'axis',formatter:ps=>esc(ps[0].name)+ps.map(p=>`<br>${p.marker}${p.seriesName}: ${p.value===null?'Não disputou':pct(p.value)}`).join('')},series:[{name:'1º turno',type:'bar',barWidth:7,itemStyle:{color:'#bdcfcf',borderRadius:[0,3,3,0]},data:ns.map(n=>one.votes[n]===undefined?null:+percent(one.votes[n],one.valid).toFixed(2))},{name:'2º turno',type:'bar',barWidth:7,itemStyle:{color:'#526b77',borderRadius:[0,3,3,0]},data:ns.map(n=>two.votes[n]===undefined?null:+percent(two.votes[n],two.valid).toFixed(2))}]});
}
let mapView={zoom:1,center:null};
function mapBounds(features){const bounds=[Infinity,Infinity,-Infinity,-Infinity];const visit=c=>{if(typeof c[0]==='number'){bounds[0]=Math.min(bounds[0],c[0]);bounds[1]=Math.min(bounds[1],c[1]);bounds[2]=Math.max(bounds[2],c[0]);bounds[3]=Math.max(bounds[3],c[1]);}else c.forEach(visit);};features.forEach(f=>visit(f.geometry.coordinates));return bounds;}
function mapLayout(){const b=mapBounds(geo.features),w=$('#map-chart').clientWidth,h=$('#map-chart').clientHeight,aspect=Math.cos((b[1]+b[3])/2*Math.PI/180);return {layoutCenter:['50%','50%'],layoutSize:Math.min(w-44,(h-38)*(b[2]-b[0])*aspect/(b[3]-b[1])),aspectScale:aspect};}
function updateMapControls(){const zoom=mapView.zoom;$('#map-zoom-level').textContent=zoom.toFixed(1)+'×';$('#map-in').disabled=zoom>=10;$('#map-out').disabled=zoom<=1;}
function moveMap(zoom,center=mapView.center){mapView={zoom:Math.max(1,Math.min(10,zoom)),center:zoom<=1?null:center};renderMap();}
function mapShade(value,max){const t=Math.max(0,Math.min(1,value/max)),a=t<.5?[224,239,235]:[129,189,176],b=t<.5?[129,189,176]:[18,107,105],f=t<.5?t*2:(t-.5)*2;return '#'+a.map((v,i)=>Math.round(v+(b[i]-v)*f).toString(16).padStart(2,'0')).join('');}
function renderMap(){
 if(mapCityKey!==state.city){mapCityKey=state.city;mapView={zoom:1,center:null};pickedLocations=[];cityMapMode='zones';}
 if(state.city){renderCityMap();return;}
 if($('#city-map-switch'))$('#city-map-switch').hidden=true;refreshCityClusters=null;
 $('#neighborhood-section').hidden=true;$('#zone-map-mode').hidden=true;$('#map-location-detail').hidden=true;$('#map-metric').hidden=false;
 $('.map-panel h2').textContent='O voto no mapa';$('.map-foot span:first-child').textContent='ALAGOAS · 102 MUNICÍPIOS';$('#map-legend').onclick=null;
 $('.map-tools span').textContent=state.neighborhood?'Mapa municipal · bairro/seção detalhadas nos demais gráficos':'Clique em um município para explorar';
 const all=data.sections.filter(s=>s.turn===state.turn);const by={};for(const s of all)(by[s.city]??=[]).push(s);cityGroups=Object.fromEntries(Object.entries(by).map(([k,v])=>[k,aggregate(v)]));
 const candidate=state.candidate||'15';const mapData=Object.entries(data.cities).map(([k,c])=>{const a=cityGroups[k],win=a.ranking[0]?.[0],value=state.metric==='absence'?percent(a.absent,a.apt):state.metric==='share'?percent(a.votes[candidate]||0,a.valid):+win,fill=state.metric==='winner'?voteHeat(a):mapShade(value,state.metric==='absence'?40:100);return{name:c.ibge,value,city:k,winner:win,itemStyle:state.metric==='winner'?{areaColor:fill||'#c1cdd2',opacity:state.city&&state.city!==k?.38:1}:undefined,select:{itemStyle:{areaColor:fill}},selected:k===state.city};});
 const bounds=mapBounds(geo.features),center=mapView.center||[(bounds[0]+bounds[2])/2,(bounds[1]+bounds[3])/2];
 const label={show:mapView.zoom>=2.5,fontSize:10,color:'#173544',textBorderColor:'#fff',textBorderWidth:3,formatter:p=>{const city=Object.values(data.cities).find(c=>c.ibge===p.name);return city?title(city.name):'';}};
 const c=setChart('map-chart',{tooltip:{...chartBase.tooltip,formatter:p=>{const d=p.data;if(!d)return '';const a=cityGroups[d.city];return `<b>${esc(title(data.cities[d.city].name))}</b><br>${esc(names[d.winner])}: ${pct(percent(a.votes[d.winner],a.valid))}<br>${fmt(a.valid)} votos válidos<br>Vantagem: ${decimal.format(voteMargin(a))} p.p.<br>Abstenção: ${pct(percent(a.absent,a.apt))}${state.metric==='share'?'<br>'+esc(names[candidate])+': '+pct(percent(a.votes[candidate]||0,a.valid)):''}`;}},visualMap:state.metric==='winner'?undefined:{show:false,min:0,max:state.metric==='absence'?40:100,inRange:{color:state.metric==='share'?['#fbf5f3',colors[candidate]]:['#e0efeb','#81bdb0','#126b69']}},series:[{type:'map',map:'AL',roam:true,scaleLimit:{min:1,max:10},...mapLayout(),zoom:mapView.zoom,center,selectedMode:'single',data:mapData,label,labelLayout:{hideOverlap:true},itemStyle:{borderColor:'#fff',borderWidth:.8,areaColor:'#178b82'},emphasis:{label:{...label,show:true},itemStyle:{borderColor:'#163e47',borderWidth:2}},select:{label:{...label,show:true},itemStyle:{borderColor:'#123b43',borderWidth:2.5}}}]});c.off('click');c.on('click',p=>{if(p.data?.city)navigate({city:p.data.city,neighborhood:'',section:''});});
 c.off('georoam');c.on('georoam',()=>{const s=c.getOption().series[0];mapView={zoom:s.zoom,center:s.center};updateMapControls();c.setOption({series:[{label:{show:mapView.zoom>=2.5}}]});});updateMapControls();
 const current=state.city&&cityGroups[state.city];$('#map-selection').innerHTML=current?`<div><span class="field-label">MUNICÍPIO SELECIONADO</span><strong>${esc(title(data.cities[state.city].name))}</strong><small>${fmt(current.valid)} votos válidos · ${fmt(current.count)} seções</small></div><div class="map-selection-actions"><button id="map-focus">Ampliar município ↗</button><button id="map-clear" aria-label="Remover seleção do município">×</button></div>`:'<div><span class="field-label">EXPLORE O ESTADO</span><strong>102 municípios, diferentes perspectivas</strong><small>Selecione no mapa ou use a busca de município nos filtros.</small></div>';
 if(current){$('#map-focus').onclick=()=>{const b=mapBounds(geo.features.filter(f=>f.properties.codarea===data.cities[state.city].ibge));moveMap(Math.min(7,Math.max(2,Math.min((bounds[2]-bounds[0])/(b[2]-b[0]),(bounds[3]-bounds[1])/(b[3]-b[1]))*.72)),[(b[0]+b[2])/2,(b[1]+b[3])/2]);};$('#map-clear').onclick=()=>navigate({city:'',neighborhood:'',section:''});}
 if(state.metric==='winner'){$('#map-legend').innerHTML=[...new Set(mapData.map(d=>d.winner))].map(n=>`<span><i class="legend-dot" style="background:${colors[n]}"></i>${esc(names[n])}</span>`).join('')+heatLegend();}else{$('#map-legend').innerHTML=`<span>${state.metric==='absence'?'Abstenção':esc(names[candidate])+' · votos válidos'} · 0%</span><span style="width:90px;height:8px;margin-top:3px;border-radius:3px;background:linear-gradient(90deg,${state.metric==='share'?'#fbf5f3,'+colors[candidate]:'#e0efeb,#126b69'})"></span><span>${state.metric==='absence'?'40%+':'100%'}</span>`;}
}
function renderProfile(a,rows){const p=a.profile;
 const sexColors={'4':'#178b82','2':'#a9c4bf','0':'#d8b582'};const sex=Object.entries(p.sex).map(([n,v])=>({name:title(data.labels.sex[n]),value:v,itemStyle:{color:sexColors[n]||'#d8b582'}}));
 setChart('sex-chart',{tooltip:{...chartBase.tooltip,trigger:'item',formatter:q=>`${esc(q.name)}<br>${fmt(q.value)} eleitores · ${pct(percent(q.value,p.total))}`},series:[{type:'pie',radius:['62%','77%'],center:['50%','51%'],avoidLabelOverlap:true,label:{show:false},itemStyle:{borderColor:'#fff',borderWidth:3},data:sex}],graphic:[{type:'text',left:'center',top:'41%',style:{text:p.total?fmt(p.total):'Sem perfil',font:'600 22px Segoe UI',fill:'#173544'}},{type:'text',left:'center',top:'57%',style:{text:'eleitores no cadastro',font:'10px Segoe UI',fill:'#789097'}}]});
 $('#sex-legend').innerHTML=sex.map(s=>`<div><span><i class="legend-dot" style="background:${s.itemStyle.color}"></i>${esc(s.name)}</span><strong>${pct(percent(s.value,p.total))}</strong></div>`).join('');
 const ages=[['Até 17',0],['18–24',0],['25–34',0],['35–44',0],['45–59',0],['60–69',0],['70+',0],['Não informado',0]];
 for(const[n,v]of Object.entries(p.age)){const label=data.labels.age[n];const age=parseInt(label);let i=!Number.isFinite(age)?7:age<18?0:age<25?1:age<35?2:age<45?3:age<60?4:age<70?5:6;ages[i][1]+=v;}
 const shown=ages.filter((a,i)=>i<7||a[1]);barProfile('age-chart',shown,p.total,'#509e91');
 const edu=Object.entries(p.education).sort((a,b)=>+a[0]-b[0]).map(([n,v])=>[title(data.labels.education[n]).replace('Ensino ','').replace('Fundamental','Fund.').replace('Superior','Sup.'),v]);barProfile('education-chart',edu,p.total,'#7a999f');
}
function barProfile(id,items,total,color){setChart(id,{grid:{left:id==='education-chart'?124:65,right:47,top:18,bottom:20},xAxis:{type:'value',show:false,max:Math.max(...items.map(x=>percent(x[1],total)),1)*1.12},yAxis:{type:'category',inverse:true,data:items.map(x=>x[0]),axisLine:{show:false},axisTick:{show:false},axisLabel:{fontSize:10,color:'#59727b'}},tooltip:{...chartBase.tooltip,formatter:p=>`${esc(p.name)}<br>${fmt(items[p.dataIndex][1])} eleitores · ${pct(p.value)}`},series:[{type:'bar',barWidth:11,data:items.map(x=>+percent(x[1],total).toFixed(2)),itemStyle:{color,borderRadius:[0,3,3,0]},label:{show:true,position:'right',fontSize:9,color:'#526b77',formatter:p=>decimal.format(p.value)+'%'}}]});}
function renderCensus(){const id=state.city?data.cities[state.city].ibge:null;const values=census.slice(1).filter(r=>!id||r.D1C===id);const totals={};for(const r of values){const v=r.V==='-'?0:Number(r.V);if(Number.isFinite(v))totals[r.D4N]=(totals[r.D4N]||0)+v;}
 $('#census-description').textContent=(id?title(data.cities[state.city].name):'Alagoas')+' · contexto '+(id?'municipal':'estadual')+(state.neighborhood?' (mantido ao filtrar bairro/seção)':'');
 $('#census-values').innerHTML=Object.entries(totals).filter(([n])=>n!=='Total').sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="census-item">${esc(n)}<strong>${pct(percent(v,totals.Total))}</strong><small>${fmt(v)} pessoas</small></div>`).join('');
}
function tableGroups(){const by={};for(const s of selected()){const k=!state.city?s.city:!state.neighborhood?s.neighborhood:s.id;(by[k]??=[]).push(s);}return Object.entries(by).map(([k,rows])=>{const a=aggregate(rows),winner=a.ranking[0]?.[0];return{k,rows,a,name:!state.city?title(data.cities[k].name):!state.neighborhood?data.neighborhoods[state.city][k].name:'Seção '+rows[0].section.padStart(4,'0'),winner:names[winner]||'Sem votos',winnerId:winner,valid:a.valid,rate:percent(a.votes[winner]||0,a.valid),absence:percent(a.absent,a.apt)}});}
function renderTable(){groups=tableGroups();filtered=groups.filter(g=>normalized(g.name+' '+g.winner+' '+(state.neighborhood?g.rows[0].place:'')).includes(normalized(state.search))).sort((a,b)=>state.direction*(typeof a[state.sort]==='number'?a[state.sort]-b[state.sort]:a[state.sort].localeCompare(b[state.sort],'pt-BR')));
 const size=8,max=Math.max(0,Math.ceil(filtered.length/size)-1);state.page=Math.min(state.page,max);const page=filtered.slice(state.page*size,(state.page+1)*size);
 $('#table-title').textContent=!state.city?'Explore os municípios':!state.neighborhood?'Explore os bairros':'Explore as seções eleitorais';$('#table-hint').textContent=state.section?'Detalhe da seção selecionada':'Use a seta para abrir o próximo nível';
 $('#table-body').innerHTML=page.length?page.map(g=>`<tr><td>${esc(g.name)}<small>${state.neighborhood?esc(title(g.rows[0].place||'Local não informado')):fmt(g.a.count)+' seções com BU'}</small></td><td><span class="table-winner"><i class="legend-dot" style="background:${colors[g.winnerId]}"></i>${esc(g.winner)}</span></td><td>${fmt(g.valid)}</td><td><span class="rate-cell">${pct(g.rate)}<i><b style="width:${g.rate}%"></b></i></span></td><td>${pct(g.absence)}</td><td>${!state.section?`<button data-drill="${g.k}" aria-label="Explorar ${esc(g.name)}">↗</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Nenhum resultado para esta busca.</td></tr>';
 $('#page-info').textContent=filtered.length?`${state.page*size+1}–${Math.min((state.page+1)*size,filtered.length)} de ${fmt(filtered.length)} registros`:'0 registros';$('#page-number').textContent=`${state.page+1} / ${max+1}`;$('#previous').disabled=state.page===0;$('#next').disabled=state.page===max;
 $$('th button').forEach(b=>{b.closest('th').setAttribute('aria-sort',b.dataset.sort===state.sort?(state.direction===1?'ascending':'descending'):'none')});
}
function exportCSV(){const candidates=Object.keys(data.candidates).filter(n=>data.candidates[n].type==='Nominal');const header=['Turno','Municipio','Bairro','Secao','Territorio','Aptos_BU','Comparecimento_BU','Abstencao_BU','Validos','Brancos','Nulos',...candidates.map(n=>names[n]+'_votos')];const rows=filtered.map(g=>[state.turn,state.city?data.cities[state.city].name:data.cities[g.k].name,state.city?data.neighborhoods[state.city][state.neighborhood||g.k].name:'',state.neighborhood?g.rows[0].section:'',g.name,g.a.apt,g.a.attendance,g.a.absent,g.a.valid,g.a.votes['95']||0,g.a.votes['96']||0,...candidates.map(n=>g.a.votes[n]??'')]);const quote=v=>'"'+String(v).replace(/"/g,'""')+'"';const text='\ufeff'+[header,...rows].map(r=>r.map(quote).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`atlas-alagoas-2022-turno-${state.turn}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bind(){
 $('#turns').addEventListener('click',e=>{const b=e.target.closest('[data-turn]');if(b){const turn=+b.dataset.turn;const valid=state.section?data.sections.some(s=>s.turn===turn&&s.city===state.city&&s.neighborhood===state.neighborhood&&s.id===state.section):true;navigate({turn,section:valid?state.section:'',candidate:turn===2&&!['15','44'].includes(state.candidate)?'':state.candidate});}});
 $('#reset').onclick=()=>navigate({city:'',neighborhood:'',section:'',candidate:'',metric:'winner'});
 $('#breadcrumbs').onclick=e=>{const b=e.target.closest('button');if(!b)return;const level=b.dataset.level;navigate(level===''?{city:'',neighborhood:'',section:''}:level==='city'?{neighborhood:'',section:''}:{section:''});};
 $('#map-metric').onchange=()=>{state.metric=$('#map-metric').value;syncFilters();renderMap()};$('#map-reset').onclick=()=>moveMap(1,null);$('#map-in').onclick=()=>moveMap(mapView.zoom*1.5);$('#map-out').onclick=()=>moveMap(mapView.zoom/1.5);
 $('#candidate-list').onclick=e=>{const b=e.target.closest('[data-candidate]');if(b){state.candidate=state.candidate===b.dataset.candidate?'':b.dataset.candidate;state.metric=state.candidate?'share':'winner';syncFilters();render();}};$('#clear-candidate').onclick=()=>navigate({candidate:'',metric:'winner'});
 $('#table-body').onclick=e=>{const b=e.target.closest('[data-drill]');if(!b)return;const k=b.dataset.drill;navigate(!state.city?{city:k,neighborhood:'',section:''}:!state.neighborhood?{neighborhood:k,section:''}:{section:k});};
 $('#table-search').oninput=()=>{state.search=$('#table-search').value;state.page=0;renderTable();};$$('[data-sort]').forEach(b=>b.onclick=()=>{state.direction=state.sort===b.dataset.sort?-state.direction:1;state.sort=b.dataset.sort;renderTable();});$('#previous').onclick=()=>{state.page--;renderTable()};$('#next').onclick=()=>{state.page++;renderTable()};$('#export').onclick=exportCSV;
 $$('.source-trigger').forEach(b=>b.onclick=()=>$('#sources').showModal());$('#close-sources').onclick=()=>$('#sources').close();$('#sources').onclick=e=>{if(e.target===$('#sources')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
 const resize=new ResizeObserver(()=>{Object.values(charts).forEach(c=>c.resize());if(charts['map-chart'])charts['map-chart'].setOption(state.city?{geo:cityMapLayout()}:{series:[mapLayout()]});if(state.city&&refreshCityClusters)refreshCityClusters();});resize.observe($('#map-chart'));resize.observe($('main'));
 const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}},{rootMargin:'-10% 0px -65% 0px'});['conteudo','territorio','perfil','detalhamento'].forEach(id=>observer.observe($('#'+id)));
}
async function init(){try{if(!window.echarts)throw Error('A biblioteca de gráficos não foi carregada. Verifique a pasta vendor.');[data,geo,census,mapLocations,neighborhoodGeo]=await Promise.all(['dados/painel-bairros.json','dados/alagoas.geojson','dados/censo-raca.json','dados/locais-votacao.json','dados/bairros-ibge.geojson'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('Arquivo indisponível: '+u);return r.json()}));
 for(const f of geo.features)f.properties.name=f.properties.codarea;echarts.registerMap('AL',geo);
 territorialFilters.city=new SearchSelect({id:'city',label:'MUNICÍPIO',all:'Todos os municípios',placeholder:'Buscar município',onChange:city=>navigate({city,neighborhood:'',section:''})});
 territorialFilters.neighborhood=new SearchSelect({id:'neighborhood',label:'BAIRRO',all:'Todos os bairros',placeholder:'Buscar bairro',onChange:neighborhood=>navigate({neighborhood,section:''})});
 territorialFilters.section=new SearchSelect({id:'section',label:'SEÇÃO',all:'Todas as seções',placeholder:'Buscar seção',onChange:section=>navigate({section})});
 const q=new URLSearchParams(location.search);if(['1','2'].includes(q.get('turn')))state.turn=+q.get('turn');if(data.cities[q.get('city')])state.city=q.get('city');if(state.city&&data.neighborhoods[state.city]?.[q.get('neighborhood')])state.neighborhood=q.get('neighborhood');if(state.neighborhood&&data.sections.some(s=>s.city===state.city&&s.neighborhood===state.neighborhood&&s.id===q.get('section')))state.section=q.get('section');if(colors[q.get('candidate')])state.candidate=q.get('candidate');if(['winner','absence','share'].includes(q.get('metric')))state.metric=q.get('metric');
 $('#dashboard').hidden=false;bind();syncFilters();render();window.atlas={state,data,aggregate,selected};
 }catch(e){$('#status').hidden=false;$('#status').textContent=e.message+' Abra o painel pelo servidor local (node scripts/servir.mjs), não diretamente como arquivo.';console.error(e);}}
init();
